WIP: Create schemas
blurg/sucuri pull request #12
Opened 2020-06-30 00:13 UTC by Serrones

Create schemas, adjust models and update migration

2020-07-12 20:17 UTC, jfunez requested changes

2020-07-12 20:17 UTC, jfunez commented on migrations/versions/f6598fcf89f5_.py
> +"""empty message
I believe that "initial migration" is better than "empty message"

2020-07-12 20:17 UTC, jfunez commented on sucuri/models/models.py
>      id = Column(Integer, primary_key=True, index=True)
move the `id` as the first attribute of the class

2020-07-12 20:22 UTC, jfunez requested changes

2020-07-12 20:22 UTC, jfunez commented on sucuri/crud/crud_profile.py
> +        raise HTTPException(status_code=404, detail="Profile not found")
replace with another exception

2020-07-12 20:35 UTC, Serrones commented on sucuri/crud/crud_profile.py
> +        raise HTTPException(status_code=404, detail="Profile not found")
This code was removed

2020-07-12 20:38 UTC, jfunez approved these changes

2020-07-13 13:08 UTC, jlugao approved these changes

2020-07-13 13:08 UTC, merged