Create DB Backend and Models
blurg/sucuri pull request #6
Opened 2020-06-21 17:51 UTC by Serrones

2020-06-22 08:11 UTC, jfunez requested changes

2020-06-22 08:11 UTC, jfunez commented on models/models.py
> +    social_media = Column(String)
acredito que podemos usar um JSON Field para armazenar as redes, tipo: 
```json
{
    "twitter": "@jfunez",
    "foo": "bar.baz"
}
```
para isso podemos ter um ENUM com as chaves das redes sociais mais populares

2020-06-22 08:11 UTC, jfunez commented on models/models.py
> +    social_media = Column(String)
o campo JSON não esta definido por padrão no SQLAlchemy por enquanto, mas podemos usar esta lib:
https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.json

2020-06-26 14:54 UTC, jlugao commented
Pra mim parece bom, só senti falta de um arquivo de migração, mas não tenho certeza sobre como isso funciona no sqlalchemy

2020-06-27 20:58 UTC, merged